version: "3.9"

services:
  postgres-v1:
    image: postgres:16-alpine
    container_name: bibliotech-db-v1
    restart: unless-stopped
    environment:
      POSTGRES_USER: bibliotech
      POSTGRES_PASSWORD: bibliotech
      POSTGRES_DB: bibliotech
    ports:
      - "5432:5432"
    volumes:
      - pgdata_v1:/var/lib/postgresql/data

  backend-v1:
    build: ./backend
    container_name: bibliotech-api-v1
    restart: unless-stopped
    depends_on:
      - postgres-v1
    environment:
      DATABASE_URL: postgresql://bibliotech:bibliotech@postgres-v1:5432/bibliotech
      JWT_SECRET: troque-este-segredo-em-producao
      PORT: 3000
    ports:
      - "3000:3000"

  frontend-v1:
    build: .
    container_name: bibliotech-web-v1
    restart: unless-stopped
    depends_on:
      - backend-v1
    ports:
      - "8080:80"

  sonarqube-v1:
    image: sonarqube:lts-community
    container_name: bibliotech-sonar-v1
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - sonar_data_v1:/opt/sonarqube/data
      - sonar_extensions_v1:/opt/sonarqube/extensions
      - sonar_logs_v1:/opt/sonarqube/logs

volumes:
  pgdata_v1:
  sonar_data_v1:
  sonar_extensions_v1:
  sonar_logs_v1:
